### PR TITLE
[PR] Adding API 

### LINKED ISSUE #53: Feat: Todo List `REST API`
Once deployed to Fly.io with CI/CD #52 and `auth` is added #37 
we should add a _basic_ `REST API` endpoint to `CRUD` Todo List items.

# Why?

As part of building a full-stack App using our chosen Tech Stack https://github.com/dwyl/technology-stack#the-petal-stack
We want to build the backend API in `Phoenix`.
This mini tutorial is the perfect place to showcase building such an API because all the ground-work is already done for Todo list `items`. 

# Todo

+ [x] in the _same_ Phoenix App, create a new `api_controller.ex` for `CRUD`-ing the `Todo` list `items` (you can use `:pipe_through :json`).
  > Remember our objective is to leverage as _much_ of the existing work in this repo as possible. 🙏 
+ [x] Create an API Endpoint for `Creating` a `new` todo list `item` and test it via `cURL` (or `Postman`) 
  + [x] Should accept a `JSON` payload with the necessary data, e.g: 
  1. `person_id` (`Int`)
  2. `status` (`Int`)
  3. `text` (`String`)

https://github.com/dwyl/phoenix-todo-list-tutorial/blob/e945ed2082e7d1f38f4eb13dc383986d26869826/lib/app/todo/item.ex#L5-L8
  + [x] Should create a new Todo `item` if the data is valid

+ [x] Create a `REST API` Endpoint for `editing` the `Todo` list `item.text`:
  + [x] Signature: `POST /items/:id/`
  + [x] Should accept the `item.id` (`Int`) and `item.text` (`String`) and return `200` if successful. 🆗 

+ [x] Create `REST API` Endpoint for Updating the `status` of the `item` i.e. setting it to "done" ✅ 

## Relevant Learning

Please read: https://github.com/dwyl/phoenix-content-negotiation-tutorial 👀 
And if you have any questions regarding content negotiation please open an issue. 🆕 

For ***`this`*** project we don't need to have all the same routes we just need:
1. Create 🆕 
2. Edit 📝 
3. Update status ✅

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #53 

This PR adds the ability for users to interact with Phoenix as an API. It should:
- create
- update
- update status

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Still very much in-progress but should be manageable.
Was stuck for a while trying to convert an `Ecto.Changeset` struct to a map but couldn't for a while. Tried several links:
- https://elixirforum.com/t/how-to-encode-ecto-schema-with-jason-with-all-fields/17221
- https://elixirforum.com/t/how-to-get-struct-from-map-elixir/4543
- https://elixirforum.com/t/convert-ecto-changeset-to-struct/3430
- https://stackoverflow.com/questions/36512627/elixir-convert-struct-to-map
- https://elixirforum.com/t/how-to-decode-a-json-into-a-struct-safely/14331
- https://elixirforum.com/t/use-ecto-schema-directly-or-convert-to-a-custom-struct/30196/3

But none were really useful. I really wanted a way of keeping the code clean to simply return a JSON object using Postman. I came across https://github.com/elixir-ecto/ecto/issues/1348 but it was an old issue and didn't really seem the idiomatic way of doing things (even if José gave the answer).

Came across https://alchemist.camp/episodes/encoding-ecto-structs-poison and it was it (though not at first). The answer was having to add the `@derive` notation on the top of the schema inside `lib/app/todo/item.ex`. The person in the video was using `Poison` but since `Jason` was being used in the project, I adapted it.

This **only works** because `Jason` is being used as the *de facto* parsing library inside `config.exs`.

```elixir
# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason
```

**Comment by LuchoTurtle** [comment]
The API routes work under the "/api" scope, as per [Phoenix 1.7rc's guide and recommendation.](https://hexdocs.pm/phoenix/1.7.0-rc.0/routing.html#scoped-routes) (even though we could use content negotiation, I personally don't see a problem with this path and it makes it simpler for the users).

I'm going to update the readme after standup.

**Comment by LuchoTurtle** [comment]
Finished adding tests. They *aren't 100%* but they technically **are**.
image

The missing lines are already covered on https://github.com/dwyl/phoenix-todo-list-tutorial/pull/56. Since this PR was created with `auth`, doesn't make sense to duplicate code and possibly making merging difficult. So it's best to merge https://github.com/dwyl/phoenix-todo-list-tutorial/pull/56 first and then this one.

If this PR is merged into `main`, I can merge `main` into this branch so coverage gets to 100%.

**Comment by LuchoTurtle** [comment]
Just added tests, a guide and referred it in the main readme. 
As I've stated before in https://github.com/dwyl/phoenix-todo-list-tutorial/pull/60#issuecomment-1349063284, this PR makes sense to only be merged  after https://github.com/dwyl/phoenix-todo-list-tutorial/pull/56. The README adds a section numbered `13`, taking into account that auth is `12`.

**Comment by nelsonic** [comment]
@LuchoTurtle please tidy the `merge-conflicts` when you can. Thanks.

**Comment by LuchoTurtle** [comment]
@nelsonic should be sorted. 👍

**Comment by nelsonic** [comment]
Thanks for fixing the `merge-conflicts`. 👍

**Comment by nelsonic** [comment]
```sh
Compiling 22 files (.ex)
warning: router paths should begin with a forward slash, got: "items"
  (phoenix 1.7.0-rc.0) lib/phoenix/router/scope.ex:113: Phoenix.Router.Scope.validate_path/1
  (phoenix 1.7.0-rc.0) lib/phoenix/router/resource.ex:31: Phoenix.Router.Resource.build/3
  lib/app_web/router.ex:35: (module)
  (elixir 1.14.1) src/elixir_compiler.erl:65: :elixir_compiler.dispatch/4
  (elixir 1.14.1) src/elixir_compiler.erl:50: :elixir_compiler.compile/3
  (elixir 1.14.1) src/elixir_module.erl:379: :elixir_module.eval_form/6
```

**Review by nelsonic — APPROVED** [review]
Great additions; thanks @LuchoTurtle! 🎉

**Pull request merged**
